Adds vessel name to gap events

diff --git a/scripts/generate_gap_events b/scripts/generate_gap_events
--- a/scripts/generate_gap_events
+++ b/scripts/generate_gap_events
@@ -4,34 +4,55 @@ source pipe-tools-utils
 THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
 source ${THIS_SCRIPT_DIR}/pipeline.sh
 ASSETS=${THIS_SCRIPT_DIR}/../assets
+ARGS=( \
+  DATE_RANGE \
+  MESSAGES_TABLE \
+  EVENTS_TABLE \
+  SEGMENT_VESSEL \
+  VESSEL_INFO \
+  MIN_POS_COUNT \
+  MIN_DIST \
+)
 
+################################################################################
+# Validate and extract arguments
+################################################################################
 display_usage() {
-	echo -e "\nUsage:\n$0 YYYY-MM-DD[,YYYY-MM-DD] MESSAGES_TABLE EVENTS_TABLE MIN_POS_COUNT MIN_DIST SEGMENT_VESSEL\n"
+	echo -e "\nUsage:\n$0 YYYY-MM-DD[,YYYY-MM-DD] MESSAGES_TABLE EVENTS_TABLE SEGMENT_VESSEL VESSEL_INFO MIN_POS_COUNT MIN_DIST\n"
 	}
 
 
-if [[ $# -ne 6  ]]
+if [[ $# -ne ${#ARGS[@]} ]]
 then
     display_usage
     exit 1
 fi
 
-DATE_RANGE=$1
-MESSAGES_TABLE=$2
-EVENTS_TABLE=$3
-MIN_POS_COUNT=$4
-MIN_DIST=$5
-SEGMENT_VESSEL=$6
+ARG_VALUES=("$@")
+PARAMS=()
+for index in ${!ARGS[*]}; do
+  echo "${ARGS[$index]}=${ARG_VALUES[$index]}"
+  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
+done
 
 IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
 if [[ -z $END_DATE ]]; then
   END_DATE=${START_DATE}
 fi
 
+echo "Running $0"
+echo "  DATE_RANGE: $DATE_RANGE"
+echo "  MESSAGES_TABLE: $MESSAGES_TABLE"
+echo "  EVENTS_TABLE: $EVENTS_TABLE"
+echo "  SEGMENT_VESSEL: $SEGMENT_VESSEL"
+echo "  VESSEL_INFO: $VESSEL_INFO"
+echo "  MIN_POS_COUNT: $MIN_POS_COUNT"
+echo "  MIN_DIST: $MIN_DIST"
 
-DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
-INSERT_SQL=${ASSETS}/bigquery/gap-events.sql.j2
-SCHEMA=${ASSETS}/bigquery/events.schema.json
+################################################################################
+# Force that the destination table exists
+################################################################################
+echo "Ensuring events table ${EVENTS_TABLE} exists"
 TABLE_DESC=(
   "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
   "* Source: ${MESSAGES_TABLE}"
@@ -40,36 +61,38 @@ TABLE_DESC=(
   "$@"
 )
 TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
-
-
-echo "Publishing gap events to ${EVENTS_TABLE}..."
-echo "${TABLE_DESC}"
-
-echo "  Create table"
-
+SCHEMA=${ASSETS}/bigquery/events.schema.json
 bq mk --force \
   --description "${TABLE_DESC}" \
   --schema ${SCHEMA} \
   --time_partitioning_field=event_start \
   ${EVENTS_TABLE}
-
 if [ "$?" -ne 0 ]; then
-  echo "  Unable to create table ${DEST_TABLE}"
+  echo "  Unable to create table ${EVENTS_TABLE}"
+  exit 1
+fi
+echo "  Events table exists"
+
+################################################################################
+# Delete existing records
+################################################################################
+DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
+echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
+jinja2 ${DELETE_SQL} \
+  -D table=${EVENTS_TABLE//:/.} \
+  -D start_date=${START_DATE} \
+  -D end_date=${END_DATE} \
+  | bq query --max_rows=0
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to delete records for table ${EVENTS_TABLE} from ${START_DATE} to ${END_DATE}"
   exit 1
 fi
 
-echo "  Deleting existing records for ${START_DATE} to ${END_DATE}"
-
-jinja2 ${DELETE_SQL} -D table=${EVENTS_TABLE//:/.} -D start_date=${START_DATE} -D end_date=${END_DATE} \
-     | bq query --max_rows=0
-
-if [ "$?" -ne 0 ]; then
-  echo "  Unable to delete records for table ${DEST_TABLE} from ${START_DATE} to ${END_DATE}"
-  exit 1
-fi
-
-echo "  Inserting new records for ${START_DATE} to ${END_DATE}"
-
+################################################################################
+# Inserting new records
+################################################################################
+INSERT_SQL=${ASSETS}/bigquery/gap-events.sql.j2
+echo "Inserting new records for ${START_DATE} to ${END_DATE}"
 jinja2 ${INSERT_SQL} \
    -D source=${MESSAGES_TABLE//:/.} \
    -D dest=${EVENTS_TABLE//:/.} \
@@ -78,11 +101,13 @@ jinja2 ${INSERT_SQL} \
    -D min_pos_count=${MIN_POS_COUNT} \
    -D min_dist=${MIN_DIST} \
    -D segment_vessel=${SEGMENT_VESSEL//:/.} \
+   -D vessel_info=${VESSEL_INFO//:/.} \
    | bq query --max_rows=0
 
+
 if [ "$?" -ne 0 ]; then
-  echo "  Unable to insert records for table ${DEST_TABLE} from ${START_DATE} to ${END_DATE}"
+  echo "  Unable to insert records for table ${EVENTS_TABLE} from ${START_DATE} to ${END_DATE}"
   exit 1
 fi
 
-echo "  ${EVENTS_TABLE} Done."
+echo "${EVENTS_TABLE} Done."
