replace append to replace in destination queries

diff --git a/scripts/generate_encounter_events_compare_tables b/scripts/generate_encounter_events_compare_tables
--- a/scripts/generate_encounter_events_compare_tables
+++ b/scripts/generate_encounter_events_compare_tables
@@ -99,17 +99,17 @@ echo "  Events table exists"
 ################################################################################
 # Delete existing records
 ################################################################################
-DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
-echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
-jinja2 ${DELETE_SQL} \
-  -D table=${current_table_name//:/.} \
-  -D start_date=${START_DATE} \
-  -D end_date=${END_DATE} \
-  | bq query --max_rows=0
-if [ "$?" -ne 0 ]; then
-  echo "  Unable to delete records for table ${current_table_name} from ${START_DATE} to ${END_DATE}"
-  exit 1
-fi
+# DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
+# echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
+# jinja2 ${DELETE_SQL} \
+#   -D table=${current_table_name//:/.} \
+#   -D start_date=${START_DATE} \
+#   -D end_date=${END_DATE} \
+#   | bq query --max_rows=0
+# if [ "$?" -ne 0 ]; then
+#   echo "  Unable to delete records for table ${current_table_name} from ${START_DATE} to ${END_DATE}"
+#   exit 1
+# fi
 
 ################################################################################
 # Inserting new records
@@ -124,7 +124,7 @@ jinja2 "${INSERT_SQL}" \
    -D spatial_measures_table=${SPATIAL_MEASURES_TABLE//:/.} \
    -D regions_table=${REGIONS_TABLE//:/.} \
    | bq query --headless --max_rows=0 --allow_large_results \
-     --append_table \
+     --replace \
      --destination_table ${current_table_name}
 
 if [ "$?" -ne 0 ]; then
