PIPELINE-3145. Ensure we truncate tables before adding new sources

diff --git a/scripts/generate_port_visits_events_v2 b/scripts/generate_port_visits_events_v2
--- a/scripts/generate_port_visits_events_v2
+++ b/scripts/generate_port_visits_events_v2
@@ -105,6 +105,18 @@ if [ "$?" -ne 0 ]; then
 fi
 echo "  Events table exists"
 
+################################################################################
+# Truncate table
+################################################################################
+TRUNCATE_SQL=${ASSETS}/bigquery/truncate-table.sql.j2
+echo "Truncating existing records in ${current_table_name}"
+jinja2 ${TRUNCATE_SQL} \
+  -D table=${current_table_name//:/.} \
+  | bq query --max_rows=0
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to truncate records for table ${current_table_name}"
+  exit 1
+fi
 
 ################################################################################
 # Inserting new records
@@ -125,7 +137,6 @@ jinja2 "${INSERT_SQL}" \
    -D start_date="${START_DATE}" \
    -D end_date="${END_DATE}" \
    | bq query --headless --max_rows=0 --allow_large_results \
-     --append_table \
      --destination_table ${current_table_name}
 
 if [ "$?" -ne 0 ]; then
