Makes the postgres import process download the json files

diff --git a/scripts/publish_postgres b/scripts/publish_postgres
--- a/scripts/publish_postgres
+++ b/scripts/publish_postgres
@@ -58,19 +58,38 @@ fi
 echo "  Exported events from ${SOURCE} to ${EXTRACT_PATH}"
 
 ################################################################################
+# Download the json files locally as it's much faster
+################################################################################
+echo "Downloading json files"
+LOCAL_JSON_PATH=./data/json
+echo "  Creating local json directory"
+mkdir -p ${LOCAL_JSON_PATH}
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to create local JSON directory"
+  exit 1
+fi
+echo "  Downloading json files"
+gsutil -m cp ${EXTRACT_PATH} ${LOCAL_JSON_PATH}
+if [ "$?" -ne 0 ]; then
+  echo "  Unable to download JSON files locally"
+  exit 1
+fi
+echo "  Downloaded JSON files"
+
+################################################################################
 # Convert format from json to exported sql format
 ################################################################################
 echo "Converting downloaded files to csv format"
 LOCAL_CSV_PATH=./data/csv
 LOCAL_CSV_FILE=${LOCAL_CSV_PATH}/data.csv
-echo "Creating local csv directory"
+echo "  Creating local csv directory"
 mkdir -p ${LOCAL_CSV_PATH}
 if [ "$?" -ne 0 ]; then
   echo "  Unable to create local CSV directory"
   exit 1
 fi
-echo "Converting json events to csv format"
-gsutil cat ${EXTRACT_PATH} | python -m pipe_events.postgis.formatter ${LOCAL_CSV_FILE}
+echo "  Converting json events to csv format"
+cat ${LOCAL_JSON_PATH}/*.json | python -m pipe_events.postgis.formatter ${LOCAL_CSV_FILE}
 if [ "$?" -ne 0 ]; then
   echo "  Unable to convert events from JSON to CSV format"
   exit 1
@@ -91,7 +110,7 @@ if [ "$?" -ne 0 ]; then
   exit 1
 fi
 
-echo "Importing data"
+echo "  Importing data"
 COPY_COMMAND="\copy ${DEST_TABLE} (event_id, event_type, vessel_id, event_start, event_end, event_info, event_vessels, event_geography, event_mean_position) from stdin with (format 'csv')"
 cat ${LOCAL_CSV_FILE} | psql -v ON_ERROR_STOP=ON "${DEST_CONNECTION_STRING}" -c "$COPY_COMMAND"
 if [ "$?" -ne 0 ]; then
@@ -99,7 +118,7 @@ if [ "$?" -ne 0 ]; then
   exit 1
 fi
 
-echo "Indexing data"
+echo "  Indexing data"
 INDEX_SQL=${ASSETS}/postgres/index.j2.sql
 jinja2 ${INDEX_SQL} \
   -D table_name=${DEST_TABLE} \
@@ -108,3 +127,5 @@ if [ "$?" -ne 0 ]; then
   echo "  Unable to set up indices for imported data"
   exit 1
 fi
+
+echo "  Done importing data"
